language: ruby
rvm:
- 2.5.3
before_install: gem install bundler
script:
- bundle exec rspec
notifications:
  slack:
    secure: ABrlEg9YOwGLlc8oq0OW4BERg9HDcmGY88LIfoEFF81XAcZLJnCdn9t3uAC31vuTgbc15/59zHTjegquz7FdTo3eeQ1aWfbJVYjioP5kgmoHQggki5LJIABwrcySkF8m6X1zzMcrxMjB1apsKywC/rr+IkzcOD4ATSY9EG0lrWX2tIL9+2D1dln4ZPBr0R2pM0pMZpnFdJ0FAr+dl6kEBs/IcVUP24eGZxTgc4gLulkPglHTC/jDEU9Zrtx/mVs4BzJzHCx8BezsMulmR5n9JD5GyWbXv+fkBlHFvOMujB3M3c5nu9vOt1rk0zsZErGMMh/TGEWcxso2HG6wLEtx6dq6PF1/rT+TfFLmA240NHaHmo4cy3ctKK3rOufyDA0Zz+ymf4jwDs/AW4on1vO9eUNrcaVumzI38R0pnTF8PwQ2rKYsvzSA62hF5A3/NavjBeh2vbLu6H9wtM/3KnF3HFIQ5S/2zj7n3Yb5T5RIgyaX5t+ZQbHTJ7mceAX5ex5+nhuCrSNqlnHUsJ9rs3bk70Zzc6PXJbnuj8URonOHfsU0r833VEkz/Khbti852KbQARoqqbJGv9UP2oqHkXTL48M+8g2W/Hq5GSdnrrfBLoRiAp30PmbqC7+5ouoKwnEor2i9HlrL4adNd60oh8WSstrkfC7fZbIpw2v/12Pu41M=
