language: ruby
rvm:
- 2.5.3
before_install: gem install bundler
script:
- bundle exec rspec
notifications:
  slack:
    secure: TpyMAqGeG5saqzCbZKpElJfPTnOxkoljTLvIBfXImE2oLbH8o91kJUrMmDn+sih/3t8PWJmNvQnB7AwikaIjgbpT3wTKgz0inl+QQo3JjByUIPHlgDT8xz1dqawGg3fxAmC3yipQilvuBCTmkfiiG3Rsois680zCGrmhVvaCFBBdgqaNQkTSDO08hr2CZKdhCFbmT+QfyZw/wYZ/Yz969qNfCSw9F4fJ2Gai/Dqp0H4Gq9Ymk4/m/Va3nY74/dcgvy7JP1aeEEjUdWrqMP1gmO8MpCrHg4JZcnA4llDa+AMma401QHE5QJNqg0VxLO1HGI7hughvvjhFk8SObH1SchyE+jsCb+ZpDL/VyfO+sj0CTnkRZhMI0S1tBtPTmZGpNn8Eqb50637LR2FeXrsZzJEKI1fdMRZN12jTXvm1XeRWR1PJdXT6iK8Vvs+WPPEmoQTkWSKxjYnbjMt91Bcp8H2BK6Pa69S08es95zi0gwur1IlRnoWwdfq8GfpGHxns2YezAbr1SpMTWR1KmoShBy8UBGYIOO5iKg7Dbrk/GFeGhLZE6FIj7clB8N996PIk+RvS2nNSeSLXIhx0Qka3zw9GoyPsQHSUY+oj/qv+9jdDBeZNkV6sRIah0ThEigG0M4kHLav7sCxzkBqBfLrfba6yYzw508BY2Fg99Zty7PU=
